import type { StoryObj } from "@storybook/react";
import { Input } from '../components/ui/input';
declare const meta: {
    title: string;
    component: typeof Input;
    tags: string[];
    decorators: ((Story: import("@storybook/core/csf").PartialStoryFn<import("@storybook/react").ReactRenderer, {
        ref?: import('../../../../node_modules/react').Ref<HTMLInputElement> | undefined;
        key?: import('../../../../node_modules/react').Key | null | undefined;
        accept?: string | undefined | undefined;
        alt?: string | undefined | undefined;
        autoComplete?: import('../../../../node_modules/react').HTMLInputAutoCompleteAttribute | undefined;
        capture?: boolean | "user" | "environment" | undefined | undefined;
        checked?: boolean | undefined | undefined;
        disabled?: boolean | undefined | undefined;
        form?: string | undefined | undefined;
        formAction?: string | ((formData: FormData) => void | Promise<void>) | undefined;
        formEncType?: string | undefined | undefined;
        formMethod?: string | undefined | undefined;
        formNoValidate?: boolean | undefined | undefined;
        formTarget?: string | undefined | undefined;
        height?: number | string | undefined | undefined;
        list?: string | undefined | undefined;
        max?: number | string | undefined | undefined;
        maxLength?: number | undefined | undefined;
        min?: number | string | undefined | undefined;
        minLength?: number | undefined | undefined;
        multiple?: boolean | undefined | undefined;
        name?: string | undefined | undefined;
        pattern?: string | undefined | undefined;
        placeholder?: string | undefined | undefined;
        readOnly?: boolean | undefined | undefined;
        required?: boolean | undefined | undefined;
        size?: number | undefined | undefined;
        src?: string | undefined | undefined;
        step?: number | string | undefined | undefined;
        type?: import('../../../../node_modules/react').HTMLInputTypeAttribute | undefined;
        value?: string | number | readonly string[] | undefined;
        width?: number | string | undefined | undefined;
        onChange?: import('../../../../node_modules/react').ChangeEventHandler<HTMLInputElement, HTMLInputElement> | undefined;
        defaultChecked?: boolean | undefined | undefined;
        defaultValue?: string | number | readonly string[] | undefined;
        suppressContentEditableWarning?: boolean | undefined | undefined;
        suppressHydrationWarning?: boolean | undefined | undefined;
        accessKey?: string | undefined | undefined;
        autoCapitalize?: "off" | "none" | "on" | "sentences" | "words" | "characters" | undefined | (string & {}) | undefined;
        autoFocus?: boolean | undefined | undefined;
        className?: string | undefined | undefined;
        contentEditable?: (boolean | "true" | "false") | "inherit" | "plaintext-only" | undefined;
        contextMenu?: string | undefined | undefined;
        dir?: string | undefined | undefined;
        draggable?: (boolean | "true" | "false") | undefined;
        enterKeyHint?: "enter" | "done" | "go" | "next" | "previous" | "search" | "send" | undefined | undefined;
        hidden?: boolean | undefined | undefined;
        id?: string | undefined | undefined;
        lang?: string | undefined | undefined;
        nonce?: string | undefined | undefined;
        slot?: string | undefined | undefined;
        spellCheck?: (boolean | "true" | "false") | undefined;
        style?: import('../../../../node_modules/react').CSSProperties | undefined;
        tabIndex?: number | undefined | undefined;
        title?: string | undefined | undefined;
        translate?: "yes" | "no" | undefined | undefined;
        radioGroup?: string | undefined | undefined;
        role?: import('../../../../node_modules/react').AriaRole | undefined;
        about?: string | undefined | undefined;
        content?: string | undefined | undefined;
        datatype?: string | undefined | undefined;
        inlist?: any;
        prefix?: string | undefined | undefined;
        property?: string | undefined | undefined;
        rel?: string | undefined | undefined;
        resource?: string | undefined | undefined;
        rev?: string | undefined | undefined;
        typeof?: string | undefined | undefined;
        vocab?: string | undefined | undefined;
        autoCorrect?: string | undefined | undefined;
        autoSave?: string | undefined | undefined;
        color?: string | undefined | undefined;
        itemProp?: string | undefined | undefined;
        itemScope?: boolean | undefined | undefined;
        itemType?: string | undefined | undefined;
        itemID?: string | undefined | undefined;
        itemRef?: string | undefined | undefined;
        results?: number | undefined | undefined;
        security?: string | undefined | undefined;
        unselectable?: "on" | "off" | undefined | undefined;
        popover?: "" | "auto" | "manual" | "hint" | undefined | undefined;
        popoverTargetAction?: "toggle" | "show" | "hide" | undefined | undefined;
        popoverTarget?: string | undefined | undefined;
        inert?: boolean | undefined | undefined;
        inputMode?: "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | "search" | undefined | undefined;
        is?: string | undefined | undefined;
        exportparts?: string | undefined | undefined;
        part?: string | undefined | undefined;
        "aria-activedescendant"?: string | undefined | undefined;
        "aria-atomic"?: (boolean | "true" | "false") | undefined;
        "aria-autocomplete"?: "none" | "inline" | "list" | "both" | undefined | undefined;
        "aria-braillelabel"?: string | undefined | undefined;
        "aria-brailleroledescription"?: string | undefined | undefined;
        "aria-busy"?: (boolean | "true" | "false") | undefined;
        "aria-checked"?: boolean | "false" | "mixed" | "true" | undefined | undefined;
        "aria-colcount"?: number | undefined | undefined;
        "aria-colindex"?: number | undefined | undefined;
        "aria-colindextext"?: string | undefined | undefined;
        "aria-colspan"?: number | undefined | undefined;
        "aria-controls"?: string | undefined | undefined;
        "aria-current"?: boolean | "false" | "true" | "page" | "step" | "location" | "date" | "time" | undefined | undefined;
        "aria-describedby"?: string | undefined | undefined;
        "aria-description"?: string | undefined | undefined;
        "aria-details"?: string | undefined | undefined;
        "aria-disabled"?: (boolean | "true" | "false") | undefined;
        "aria-dropeffect"?: "none" | "copy" | "execute" | "link" | "move" | "popup" | undefined | undefined;
        "aria-errormessage"?: string | undefined | undefined;
        "aria-expanded"?: (boolean | "true" | "false") | undefined;
        "aria-flowto"?: string | undefined | undefined;
        "aria-grabbed"?: (boolean | "true" | "false") | undefined;
        "aria-haspopup"?: boolean | "false" | "true" | "menu" | "listbox" | "tree" | "grid" | "dialog" | undefined | undefined;
        "aria-hidden"?: (boolean | "true" | "false") | undefined;
        "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined | undefined;
        "aria-keyshortcuts"?: string | undefined | undefined;
        "aria-label"?: string | undefined | undefined;
        "aria-labelledby"?: string | undefined | undefined;
        "aria-level"?: number | undefined | undefined;
        "aria-live"?: "off" | "assertive" | "polite" | undefined | undefined;
        "aria-modal"?: (boolean | "true" | "false") | undefined;
        "aria-multiline"?: (boolean | "true" | "false") | undefined;
        "aria-multiselectable"?: (boolean | "true" | "false") | undefined;
        "aria-orientation"?: "horizontal" | "vertical" | undefined | undefined;
        "aria-owns"?: string | undefined | undefined;
        "aria-placeholder"?: string | undefined | undefined;
        "aria-posinset"?: number | undefined | undefined;
        "aria-pressed"?: boolean | "false" | "mixed" | "true" | undefined | undefined;
        "aria-readonly"?: (boolean | "true" | "false") | undefined;
        "aria-relevant"?: "additions" | "additions removals" | "additions text" | "all" | "removals" | "removals additions" | "removals text" | "text" | "text additions" | "text removals" | undefined | undefined;
        "aria-required"?: (boolean | "true" | "false") | undefined;
        "aria-roledescription"?: string | undefined | undefined;
        "aria-rowcount"?: number | undefined | undefined;
        "aria-rowindex"?: number | undefined | undefined;
        "aria-rowindextext"?: string | undefined | undefined;
        "aria-rowspan"?: number | undefined | undefined;
        "aria-selected"?: (boolean | "true" | "false") | undefined;
        "aria-setsize"?: number | undefined | undefined;
        "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined | undefined;
        "aria-valuemax"?: number | undefined | undefined;
        "aria-valuemin"?: number | undefined | undefined;
        "aria-valuenow"?: number | undefined | undefined;
        "aria-valuetext"?: string | undefined | undefined;
        children?: import('../../../../node_modules/react').ReactNode;
        dangerouslySetInnerHTML?: {
            __html: string | TrustedHTML;
        } | undefined | undefined;
        onCopy?: import('../../../../node_modules/react').ClipboardEventHandler<HTMLInputElement> | undefined;
        onCopyCapture?: import('../../../../node_modules/react').ClipboardEventHandler<HTMLInputElement> | undefined;
        onCut?: import('../../../../node_modules/react').ClipboardEventHandler<HTMLInputElement> | undefined;
        onCutCapture?: import('../../../../node_modules/react').ClipboardEventHandler<HTMLInputElement> | undefined;
        onPaste?: import('../../../../node_modules/react').ClipboardEventHandler<HTMLInputElement> | undefined;
        onPasteCapture?: import('../../../../node_modules/react').ClipboardEventHandler<HTMLInputElement> | undefined;
        onCompositionEnd?: import('../../../../node_modules/react').CompositionEventHandler<HTMLInputElement> | undefined;
        onCompositionEndCapture?: import('../../../../node_modules/react').CompositionEventHandler<HTMLInputElement> | undefined;
        onCompositionStart?: import('../../../../node_modules/react').CompositionEventHandler<HTMLInputElement> | undefined;
        onCompositionStartCapture?: import('../../../../node_modules/react').CompositionEventHandler<HTMLInputElement> | undefined;
        onCompositionUpdate?: import('../../../../node_modules/react').CompositionEventHandler<HTMLInputElement> | undefined;
        onCompositionUpdateCapture?: import('../../../../node_modules/react').CompositionEventHandler<HTMLInputElement> | undefined;
        onFocus?: import('../../../../node_modules/react').FocusEventHandler<HTMLInputElement> | undefined;
        onFocusCapture?: import('../../../../node_modules/react').FocusEventHandler<HTMLInputElement> | undefined;
        onBlur?: import('../../../../node_modules/react').FocusEventHandler<HTMLInputElement> | undefined;
        onBlurCapture?: import('../../../../node_modules/react').FocusEventHandler<HTMLInputElement> | undefined;
        onChangeCapture?: import('../../../../node_modules/react').ChangeEventHandler<HTMLInputElement, Element> | undefined;
        onBeforeInput?: import('../../../../node_modules/react').InputEventHandler<HTMLInputElement> | undefined;
        onBeforeInputCapture?: import('../../../../node_modules/react').InputEventHandler<HTMLInputElement> | undefined;
        onInput?: import('../../../../node_modules/react').InputEventHandler<HTMLInputElement> | undefined;
        onInputCapture?: import('../../../../node_modules/react').InputEventHandler<HTMLInputElement> | undefined;
        onReset?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onResetCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onSubmit?: import('../../../../node_modules/react').SubmitEventHandler<HTMLInputElement> | undefined;
        onSubmitCapture?: import('../../../../node_modules/react').SubmitEventHandler<HTMLInputElement> | undefined;
        onInvalid?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onInvalidCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onLoad?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onLoadCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onError?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onErrorCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onKeyDown?: import('../../../../node_modules/react').KeyboardEventHandler<HTMLInputElement> | undefined;
        onKeyDownCapture?: import('../../../../node_modules/react').KeyboardEventHandler<HTMLInputElement> | undefined;
        onKeyPress?: import('../../../../node_modules/react').KeyboardEventHandler<HTMLInputElement> | undefined;
        onKeyPressCapture?: import('../../../../node_modules/react').KeyboardEventHandler<HTMLInputElement> | undefined;
        onKeyUp?: import('../../../../node_modules/react').KeyboardEventHandler<HTMLInputElement> | undefined;
        onKeyUpCapture?: import('../../../../node_modules/react').KeyboardEventHandler<HTMLInputElement> | undefined;
        onAbort?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onAbortCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onCanPlay?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onCanPlayCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onCanPlayThrough?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onCanPlayThroughCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onDurationChange?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onDurationChangeCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onEmptied?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onEmptiedCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onEncrypted?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onEncryptedCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onEnded?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onEndedCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onLoadedData?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onLoadedDataCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onLoadedMetadata?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onLoadedMetadataCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onLoadStart?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onLoadStartCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onPause?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onPauseCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onPlay?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onPlayCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onPlaying?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onPlayingCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onProgress?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onProgressCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onRateChange?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onRateChangeCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onSeeked?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onSeekedCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onSeeking?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onSeekingCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onStalled?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onStalledCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onSuspend?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onSuspendCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onTimeUpdate?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onTimeUpdateCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onVolumeChange?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onVolumeChangeCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onWaiting?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onWaitingCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onAuxClick?: import('../../../../node_modules/react').MouseEventHandler<HTMLInputElement> | undefined;
        onAuxClickCapture?: import('../../../../node_modules/react').MouseEventHandler<HTMLInputElement> | undefined;
        onClick?: import('../../../../node_modules/react').MouseEventHandler<HTMLInputElement> | undefined;
        onClickCapture?: import('../../../../node_modules/react').MouseEventHandler<HTMLInputElement> | undefined;
        onContextMenu?: import('../../../../node_modules/react').MouseEventHandler<HTMLInputElement> | undefined;
        onContextMenuCapture?: import('../../../../node_modules/react').MouseEventHandler<HTMLInputElement> | undefined;
        onDoubleClick?: import('../../../../node_modules/react').MouseEventHandler<HTMLInputElement> | undefined;
        onDoubleClickCapture?: import('../../../../node_modules/react').MouseEventHandler<HTMLInputElement> | undefined;
        onDrag?: import('../../../../node_modules/react').DragEventHandler<HTMLInputElement> | undefined;
        onDragCapture?: import('../../../../node_modules/react').DragEventHandler<HTMLInputElement> | undefined;
        onDragEnd?: import('../../../../node_modules/react').DragEventHandler<HTMLInputElement> | undefined;
        onDragEndCapture?: import('../../../../node_modules/react').DragEventHandler<HTMLInputElement> | undefined;
        onDragEnter?: import('../../../../node_modules/react').DragEventHandler<HTMLInputElement> | undefined;
        onDragEnterCapture?: import('../../../../node_modules/react').DragEventHandler<HTMLInputElement> | undefined;
        onDragExit?: import('../../../../node_modules/react').DragEventHandler<HTMLInputElement> | undefined;
        onDragExitCapture?: import('../../../../node_modules/react').DragEventHandler<HTMLInputElement> | undefined;
        onDragLeave?: import('../../../../node_modules/react').DragEventHandler<HTMLInputElement> | undefined;
        onDragLeaveCapture?: import('../../../../node_modules/react').DragEventHandler<HTMLInputElement> | undefined;
        onDragOver?: import('../../../../node_modules/react').DragEventHandler<HTMLInputElement> | undefined;
        onDragOverCapture?: import('../../../../node_modules/react').DragEventHandler<HTMLInputElement> | undefined;
        onDragStart?: import('../../../../node_modules/react').DragEventHandler<HTMLInputElement> | undefined;
        onDragStartCapture?: import('../../../../node_modules/react').DragEventHandler<HTMLInputElement> | undefined;
        onDrop?: import('../../../../node_modules/react').DragEventHandler<HTMLInputElement> | undefined;
        onDropCapture?: import('../../../../node_modules/react').DragEventHandler<HTMLInputElement> | undefined;
        onMouseDown?: import('../../../../node_modules/react').MouseEventHandler<HTMLInputElement> | undefined;
        onMouseDownCapture?: import('../../../../node_modules/react').MouseEventHandler<HTMLInputElement> | undefined;
        onMouseEnter?: import('../../../../node_modules/react').MouseEventHandler<HTMLInputElement> | undefined;
        onMouseLeave?: import('../../../../node_modules/react').MouseEventHandler<HTMLInputElement> | undefined;
        onMouseMove?: import('../../../../node_modules/react').MouseEventHandler<HTMLInputElement> | undefined;
        onMouseMoveCapture?: import('../../../../node_modules/react').MouseEventHandler<HTMLInputElement> | undefined;
        onMouseOut?: import('../../../../node_modules/react').MouseEventHandler<HTMLInputElement> | undefined;
        onMouseOutCapture?: import('../../../../node_modules/react').MouseEventHandler<HTMLInputElement> | undefined;
        onMouseOver?: import('../../../../node_modules/react').MouseEventHandler<HTMLInputElement> | undefined;
        onMouseOverCapture?: import('../../../../node_modules/react').MouseEventHandler<HTMLInputElement> | undefined;
        onMouseUp?: import('../../../../node_modules/react').MouseEventHandler<HTMLInputElement> | undefined;
        onMouseUpCapture?: import('../../../../node_modules/react').MouseEventHandler<HTMLInputElement> | undefined;
        onSelect?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onSelectCapture?: import('../../../../node_modules/react').ReactEventHandler<HTMLInputElement> | undefined;
        onTouchCancel?: import('../../../../node_modules/react').TouchEventHandler<HTMLInputElement> | undefined;
        onTouchCancelCapture?: import('../../../../node_modules/react').TouchEventHandler<HTMLInputElement> | undefined;
        onTouchEnd?: import('../../../../node_modules/react').TouchEventHandler<HTMLInputElement> | undefined;
        onTouchEndCapture?: import('../../../../node_modules/react').TouchEventHandler<HTMLInputElement> | undefined;
        onTouchMove?: import('../../../../node_modules/react').TouchEventHandler<HTMLInputElement> | undefined;
        onTouchMoveCapture?: import('../../../../node_modules/react').TouchEventHandler<HTMLInputElement> | undefined;
        onTouchStart?: import('../../../../node_modules/react').TouchEventHandler<HTMLInputElement> | undefined;
        onTouchStartCapture?: import('../../../../node_modules/react').TouchEventHandler<HTMLInputElement> | undefined;
        onPointerDown?: import('../../../../node_modules/react').PointerEventHandler<HTMLInputElement> | undefined;
        onPointerDownCapture?: import('../../../../node_modules/react').PointerEventHandler<HTMLInputElement> | undefined;
        onPointerMove?: import('../../../../node_modules/react').PointerEventHandler<HTMLInputElement> | undefined;
        onPointerMoveCapture?: import('../../../../node_modules/react').PointerEventHandler<HTMLInputElement> | undefined;
        onPointerUp?: import('../../../../node_modules/react').PointerEventHandler<HTMLInputElement> | undefined;
        onPointerUpCapture?: import('../../../../node_modules/react').PointerEventHandler<HTMLInputElement> | undefined;
        onPointerCancel?: import('../../../../node_modules/react').PointerEventHandler<HTMLInputElement> | undefined;
        onPointerCancelCapture?: import('../../../../node_modules/react').PointerEventHandler<HTMLInputElement> | undefined;
        onPointerEnter?: import('../../../../node_modules/react').PointerEventHandler<HTMLInputElement> | undefined;
        onPointerLeave?: import('../../../../node_modules/react').PointerEventHandler<HTMLInputElement> | undefined;
        onPointerOver?: import('../../../../node_modules/react').PointerEventHandler<HTMLInputElement> | undefined;
        onPointerOverCapture?: import('../../../../node_modules/react').PointerEventHandler<HTMLInputElement> | undefined;
        onPointerOut?: import('../../../../node_modules/react').PointerEventHandler<HTMLInputElement> | undefined;
        onPointerOutCapture?: import('../../../../node_modules/react').PointerEventHandler<HTMLInputElement> | undefined;
        onGotPointerCapture?: import('../../../../node_modules/react').PointerEventHandler<HTMLInputElement> | undefined;
        onGotPointerCaptureCapture?: import('../../../../node_modules/react').PointerEventHandler<HTMLInputElement> | undefined;
        onLostPointerCapture?: import('../../../../node_modules/react').PointerEventHandler<HTMLInputElement> | undefined;
        onLostPointerCaptureCapture?: import('../../../../node_modules/react').PointerEventHandler<HTMLInputElement> | undefined;
        onScroll?: import('../../../../node_modules/react').UIEventHandler<HTMLInputElement> | undefined;
        onScrollCapture?: import('../../../../node_modules/react').UIEventHandler<HTMLInputElement> | undefined;
        onScrollEnd?: import('../../../../node_modules/react').UIEventHandler<HTMLInputElement> | undefined;
        onScrollEndCapture?: import('../../../../node_modules/react').UIEventHandler<HTMLInputElement> | undefined;
        onWheel?: import('../../../../node_modules/react').WheelEventHandler<HTMLInputElement> | undefined;
        onWheelCapture?: import('../../../../node_modules/react').WheelEventHandler<HTMLInputElement> | undefined;
        onAnimationStart?: import('../../../../node_modules/react').AnimationEventHandler<HTMLInputElement> | undefined;
        onAnimationStartCapture?: import('../../../../node_modules/react').AnimationEventHandler<HTMLInputElement> | undefined;
        onAnimationEnd?: import('../../../../node_modules/react').AnimationEventHandler<HTMLInputElement> | undefined;
        onAnimationEndCapture?: import('../../../../node_modules/react').AnimationEventHandler<HTMLInputElement> | undefined;
        onAnimationIteration?: import('../../../../node_modules/react').AnimationEventHandler<HTMLInputElement> | undefined;
        onAnimationIterationCapture?: import('../../../../node_modules/react').AnimationEventHandler<HTMLInputElement> | undefined;
        onToggle?: import('../../../../node_modules/react').ToggleEventHandler<HTMLInputElement> | undefined;
        onBeforeToggle?: import('../../../../node_modules/react').ToggleEventHandler<HTMLInputElement> | undefined;
        onTransitionCancel?: import('../../../../node_modules/react').TransitionEventHandler<HTMLInputElement> | undefined;
        onTransitionCancelCapture?: import('../../../../node_modules/react').TransitionEventHandler<HTMLInputElement> | undefined;
        onTransitionEnd?: import('../../../../node_modules/react').TransitionEventHandler<HTMLInputElement> | undefined;
        onTransitionEndCapture?: import('../../../../node_modules/react').TransitionEventHandler<HTMLInputElement> | undefined;
        onTransitionRun?: import('../../../../node_modules/react').TransitionEventHandler<HTMLInputElement> | undefined;
        onTransitionRunCapture?: import('../../../../node_modules/react').TransitionEventHandler<HTMLInputElement> | undefined;
        onTransitionStart?: import('../../../../node_modules/react').TransitionEventHandler<HTMLInputElement> | undefined;
        onTransitionStartCapture?: import('../../../../node_modules/react').TransitionEventHandler<HTMLInputElement> | undefined;
    }>) => import('../../../../node_modules/react/jsx-runtime').JSX.Element)[];
    args: {
        placeholder: string;
        disabled: false;
    };
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Playground: Story;
export declare const Disabled: Story;
