import * as React from '../../../../../../node_modules/react';
import type { ElementType } from '../../../../../../node_modules/react';
import { type TypographyColorType, type TypographyType } from '../../../components/atoms/Typography';
type EditableTypographyPropertyType = {
    className?: string;
    contentClassName?: string;
    typography?: TypographyType;
    element?: ElementType;
    color?: TypographyColorType;
    isEditModeDisabled?: boolean;
    isEditModeOn?: boolean;
    isLoading?: boolean;
    value?: string;
    defaultValue?: string;
    placeholder?: string;
    onValueChange?: (value: string) => void;
    onEditModeChange?: (isEditModeOn: boolean) => void;
    children?: React.ReactNode;
};
export declare const EditableTypography: ({ className, contentClassName, typography, element, color, isEditModeDisabled, isEditModeOn, isLoading, value, defaultValue, placeholder, onValueChange, onEditModeChange, children, }: EditableTypographyPropertyType) => import('../../../../../../node_modules/react/jsx-runtime').JSX.Element;
export {};
