import * as React from '../../../../../../../node_modules/react';
import { type ImagePropertyType } from '../../../../components/atoms/Image';
import { type TagType } from '../../../../components/atoms/Tag';
import { type TypographyColorType } from '../../../../components/atoms/Typography';
export type StoreSlideImageChangePayloadType = {
    file: File;
    objectUrl: string;
};
export type StoreSlideTagItemType = {
    id: string;
    label: string;
    type?: TagType;
    position?: 'top-left' | 'bottom-right';
    color?: TypographyColorType;
    textColor?: TypographyColorType;
    isLoading?: boolean;
    onClick?: (id: string) => void;
    onLabelChange?: (id: string, value: string) => void;
};
export type StoreSlidePropertyType = Omit<React.HTMLAttributes<HTMLElement>, 'title'> & {
    isSetModeEnabled?: boolean;
    isEditModeEnabled?: boolean;
    isEditModeDisabled?: boolean;
    setModelEnabled?: boolean;
    coverImageSrc: string;
    coverImageAlt?: string;
    isImageLoading?: boolean;
    imageProps?: Omit<ImagePropertyType, 'src' | 'alt' | 'className'>;
    imageAccept?: string;
    onImageChange?: (payload: StoreSlideImageChangePayloadType) => void;
    brandName: React.ReactNode;
    brandIcon?: React.ReactNode;
    heading: React.ReactNode;
    accentText?: React.ReactNode;
    description?: React.ReactNode;
    priceText: React.ReactNode;
    tagText?: string;
    tagType?: TagType;
    tagColor?: TypographyColorType;
    tagTextColor?: TypographyColorType;
    tags?: StoreSlideTagItemType[];
    onTagClick?: (id: string) => void;
    onTagLabelChange?: (id: string, value: string) => void;
    badgeText?: React.ReactNode;
};
export declare const StoreSlide: ({ className, isSetModeEnabled, isEditModeEnabled, isEditModeDisabled, setModelEnabled, coverImageSrc, coverImageAlt, isImageLoading, imageProps, imageAccept, onImageChange, brandName, brandIcon, heading, accentText, description, priceText, tagText, tagType, tagColor, tagTextColor, tags, onTagClick, onTagLabelChange, badgeText, ...property }: StoreSlidePropertyType) => import('../../../../../../../node_modules/react/jsx-runtime').JSX.Element;
