import * as React from '../../../../../../../node_modules/react';
import { type ImagePropertyType } from '../../../../components/atoms/Image';
import { type TagType } from '../../../../components/atoms/Tag';
import { type TypographyColorType } from '../../../../components/atoms/Typography';
export type StoreSlideImageChangePayloadType = {
    file: File;
    objectUrl: string;
};
type StoreSlidePropertyType = Omit<React.HTMLAttributes<HTMLElement>, 'title'> & {
    isSetModeEnabled?: boolean;
    setModelEnabled?: boolean;
    coverImageSrc: string;
    coverImageAlt?: string;
    isImageLoading?: boolean;
    imageProps?: Omit<ImagePropertyType, 'src' | 'alt' | 'className'>;
    imageAccept?: string;
    onImageChange?: (payload: StoreSlideImageChangePayloadType) => void;
    brandName: React.ReactNode;
    brandIcon?: React.ReactNode;
    heading: React.ReactNode;
    accentText?: React.ReactNode;
    description?: React.ReactNode;
    priceText: React.ReactNode;
    tagText?: string;
    tagType?: TagType;
    tagColor?: TypographyColorType;
    tagTextColor?: TypographyColorType;
    badgeText?: React.ReactNode;
};
export declare const StoreSlide: ({ className, isSetModeEnabled, setModelEnabled, coverImageSrc, coverImageAlt, isImageLoading, imageProps, imageAccept, onImageChange, brandName, brandIcon, heading, accentText, description, priceText, tagText, tagType, tagColor, tagTextColor, badgeText, ...property }: StoreSlidePropertyType) => import('../../../../../../../node_modules/react/jsx-runtime').JSX.Element;
export {};
